describe('E2E Tests Login /Logout Flow', () => {
  it('Should NOT Log in with Invalid credentials', () => {
    browser.url('http://zero.webappsecurity.com/index.html')
    const button  = $('#signin_button')
    button.waitForExist()
    button.click()
    const loginForm = $('#login_form')
    loginForm.waitForExist()
    const login = $('#user_login')
    login.setValue('invalid')
    const password = $('#user_password')
    password.setValue('invalid')
    $('input[type="submit"]').click()
    const error = $('.alert-error')
    expect(error).toHaveText('Login and/or password are wrong.')
  })
  it('Should Log in with Valid credentials', () => {
    browser.url('http://zero.webappsecurity.com/index.html')
    const button  = $('#signin_button')
    button.waitForExist()
    button.click()
    const loginForm = $('#login_form')
    loginForm.waitForExist()
    const login = $('#user_login')
    login.setValue('username')
    const password = $('#user_password')
    password.setValue('password')
    $('input[type="submit"]').click()
    const navtabs = $('.nav-tabs')
    navtabs.waitForExist()
  })
  it('Logout', () => {
    const user = $('.icon-user')
    user.waitForExist()
    user.click()
    const logoutLink = $('#logout_link')
    logoutLink.waitForExist()
    logoutLink.click()
    const signInBtn  = $('#signin_button')
    signInBtn.waitForExist()
  })
})